### ISSUE TITLE
Specify LCM bus in yaml files

### ISSUE THREAD

**Issue by nepfaff** [nepfaff/iiwa_setup#16]
A change makes it necessary to specify the LCM bus. The following should fix the issues:
```
model_drivers:
        iiwa: !IiwaDriver
            lcm_bus: "default"
lcm_buses:
        default:
            lcm_url: ""
```

The task of this issue is to add this to all yaml configs and test it with the real robot.
